// Copyright 2024 Accenture.

// IGNORE_INCLUDE_GUARD_CHECK

#if defined(BSP_IO_PIN_CONFIGURATION) && (BSP_IO_PIN_CONFIGURATION == 1)

// S32K3xx IO Configuration
// This is a basic configuration for S32K312/S32K344
// UART0 pins are configured for console output

Io::PinConfiguration const Io::fPinConfiguration[Io::NUMBER_OF_IOS] = {
    // clang-format off

    // Port A pins (PA0-PA31)
    /* 00  */ {_PORTA_, PA0, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, GPIO},
    /* 01  */ {_PORTA_, PA1, _OUT, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, (uint32_t) GPIO | (uint32_t) STRENGTH_ON},
    /* 02  */ {_PORTA_, PA2, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 03  */ {_PORTA_, PA3, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 04  */ {_PORTA_, PA4, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 05  */ {_PORTA_, PA5, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 06  */ {_PORTA_, PA6, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 07  */ {_PORTA_, PA7, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 08  */ {_PORTA_, PA8, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 09  */ {_PORTA_, PA9, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 10  */ {_PORTA_, PA10, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 11  */ {_PORTA_, PA11, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 12  */ {_PORTA_, PA12, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 13  */ {_PORTA_, PA13, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 14  */ {_PORTA_, PA14, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 15  */ {_PORTA_, PA15, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 16  */ {_PORTA_, PA16, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 17  */ {_PORTA_, PA17, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 18  */ {_PORTA_, PA18, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 19  */ {_PORTA_, PA19, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 20  */ {_PORTA_, PA20, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 21  */ {_PORTA_, PA21, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 22  */ {_PORTA_, PA22, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 23  */ {_PORTA_, PA23, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 24  */ {_PORTA_, PA24, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 25  */ {_PORTA_, PA25, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 26  */ {_PORTA_, PA26, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 27  */ {_PORTA_, PA27, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 28  */ {_PORTA_, PA28, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 29  */ {_PORTA_, PA29, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 30  */ {_PORTA_, PA30, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 31  */ {_PORTA_, PA31, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},

    // Port B pins (PB0-PB31)
    /* 32  */ {_PORTB_, PB0, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 33  */ {_PORTB_, PB1, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 34  */ {_PORTB_, PB2, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 35  */ {_PORTB_, PB3, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 36  */ {_PORTB_, PB4, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 37  */ {_PORTB_, PB5, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 38  */ {_PORTB_, PB6, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 39  */ {_PORTB_, PB7, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 40  */ {_PORTB_, PB8, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 41  */ {_PORTB_, PB9, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 42  */ {_PORTB_, PB10, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 43  */ {_PORTB_, PB11, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 44  */ {_PORTB_, PB12, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 45  */ {_PORTB_, PB13, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 46  */ {_PORTB_, PB14, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 47  */ {_PORTB_, PB15, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 48  */ {_PORTB_, PB16, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 49  */ {_PORTB_, PB17, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 50  */ {_PORTB_, PB18, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 51  */ {_PORTB_, PB19, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 52  */ {_PORTB_, PB20, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 53  */ {_PORTB_, PB21, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 54  */ {_PORTB_, PB22, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 55  */ {_PORTB_, PB23, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 56  */ {_PORTB_, PB24, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 57  */ {_PORTB_, PB25, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 58  */ {_PORTB_, PB26, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 59  */ {_PORTB_, PB27, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 60  */ {_PORTB_, PB28, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 61  */ {_PORTB_, PB29, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 62  */ {_PORTB_, PB30, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 63  */ {_PORTB_, PB31, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},

    // Port C pins (PC0-PC31)
    /* 64  */ {_PORTC_, PC0, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 65  */ {_PORTC_, PC1, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 66  */ {_PORTC_, PC2, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 67  */ {_PORTC_, PC3, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 68  */ {_PORTC_, PC4, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 69  */ {_PORTC_, PC5, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 70  */ {_PORTC_, PC6, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 71  */ {_PORTC_, PC7, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 72  */ {_PORTC_, PC8, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 73  */ {_PORTC_, PC9, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 74  */ {_PORTC_, PC10, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 75  */ {_PORTC_, PC11, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 76  */ {_PORTC_, PC12, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 77  */ {_PORTC_, PC13, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 78  */ {_PORTC_, PC14, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 79  */ {_PORTC_, PC15, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 80  */ {_PORTC_, PC16, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 81  */ {_PORTC_, PC17, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 82  */ {_PORTC_, PC18, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 83  */ {_PORTC_, PC19, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 84  */ {_PORTC_, PC20, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 85  */ {_PORTC_, PC21, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 86  */ {_PORTC_, PC22, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 87  */ {_PORTC_, PC23, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 88  */ {_PORTC_, PC24, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 89  */ {_PORTC_, PC25, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 90  */ {_PORTC_, PC26, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 91  */ {_PORTC_, PC27, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 92  */ {_PORTC_, PC28, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 93  */ {_PORTC_, PC29, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 94  */ {_PORTC_, PC30, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 95  */ {_PORTC_, PC31, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},

    // Port D pins (PD0-PD31)
    /* 96  */ {_PORTD_, PD0, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 97  */ {_PORTD_, PD1, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 98  */ {_PORTD_, PD2, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 99  */ {_PORTD_, PD3, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 100 */ {_PORTD_, PD4, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 101 */ {_PORTD_, PD5, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 102 */ {_PORTD_, PD6, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 103 */ {_PORTD_, PD7, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 104 */ {_PORTD_, PD8, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 105 */ {_PORTD_, PD9, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 106 */ {_PORTD_, PD10, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 107 */ {_PORTD_, PD11, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 108 */ {_PORTD_, PD12, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 109 */ {_PORTD_, PD13, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 110 */ {_PORTD_, PD14, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 111 */ {_PORTD_, PD15, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 112 */ {_PORTD_, PD16, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 113 */ {_PORTD_, PD17, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 114 */ {_PORTD_, PD18, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 115 */ {_PORTD_, PD19, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 116 */ {_PORTD_, PD20, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 117 */ {_PORTD_, PD21, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 118 */ {_PORTD_, PD22, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 119 */ {_PORTD_, PD23, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 120 */ {_PORTD_, PD24, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 121 */ {_PORTD_, PD25, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 122 */ {_PORTD_, PD26, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 123 */ {_PORTD_, PD27, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 124 */ {_PORTD_, PD28, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 125 */ {_PORTD_, PD29, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 126 */ {_PORTD_, PD30, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 127 */ {_PORTD_, PD31, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},

    // Port E pins (PE0-PE31)
    /* 128 */ {_PORTE_, PE0, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 129 */ {_PORTE_, PE1, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 130 */ {_PORTE_, PE2, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 131 */ {_PORTE_, PE3, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 132 */ {_PORTE_, PE4, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 133 */ {_PORTE_, PE5, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 134 */ {_PORTE_, PE6, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 135 */ {_PORTE_, PE7, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 136 */ {_PORTE_, PE8, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 137 */ {_PORTE_, PE9, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 138 */ {_PORTE_, PE10, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 139 */ {_PORTE_, PE11, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 140 */ {_PORTE_, PE12, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 141 */ {_PORTE_, PE13, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 142 */ {_PORTE_, PE14, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 143 */ {_PORTE_, PE15, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 144 */ {_PORTE_, PE16, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 145 */ {_PORTE_, PE17, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 146 */ {_PORTE_, PE18, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 147 */ {_PORTE_, PE19, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 148 */ {_PORTE_, PE20, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 149 */ {_PORTE_, PE21, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 150 */ {_PORTE_, PE22, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 151 */ {_PORTE_, PE23, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 152 */ {_PORTE_, PE24, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 153 */ {_PORTE_, PE25, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 154 */ {_PORTE_, PE26, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 155 */ {_PORTE_, PE27, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 156 */ {_PORTE_, PE28, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 157 */ {_PORTE_, PE29, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 158 */ {_PORTE_, PE30, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 159 */ {_PORTE_, PE31, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},

    // UART pin definitions for S32K3xx
    // UART0_TX - Configure as LPUART0 TX (typically PC6 or PC7)
    /* 200 */ {_PORTC_, PC6, _OUT, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, (uint32_t) ALT2 | (uint32_t) STRENGTH_ON},
    /* 201 */ {_PORTC_, PC7, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, (uint32_t) ALT2},
    
    // UART1_TX/RX - Configure as LPUART1 TX/RX
    /* 202 */ {_PORTC_, PC8, _OUT, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, (uint32_t) ALT2 | (uint32_t) STRENGTH_ON},
    /* 203 */ {_PORTC_, PC9, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, (uint32_t) ALT2},
    
    // UART2_TX/RX - Configure as LPUART2 TX/RX
    /* 204 */ {_PORTC_, PC10, _OUT, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, (uint32_t) ALT2 | (uint32_t) STRENGTH_ON},
    /* 205 */ {_PORTC_, PC11, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, (uint32_t) ALT2},
    
    // UART3_TX/RX - Configure as LPUART3 TX/RX
    /* 206 */ {_PORTC_, PC12, _OUT, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, (uint32_t) ALT2 | (uint32_t) STRENGTH_ON},
    /* 207 */ {_PORTC_, PC13, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, (uint32_t) ALT2},

    // clang-format on
};

// Define the number of inputs and outputs
#define NUMBER_OF_INPUTS_AND_OUTPUTS 208

#endif
